development:
  bucket: myrestaurantdevelopment
  access_key_id: AKIAJKQRXAEKUFEMDN3Q
  secret_access_key: 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

test:
  bucket: myrestauranttest
  access_key_id: AKIAJKQRXAEKUFEMDN3Q
  secret_access_key: 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

production:
  bucket: myrestaurant
  access_key_id: AKIAJKQRXAEKUFEMDN3Q
  secret_access_key: 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